
AMBER_MQTT_PREFIX = "ambermqtt"
AMBER_DEVICE_ID = "amber2mqtt"
AMBER_DEVICE_NAME = "Amber 2 MQTT"
AMBER_DEVICE_MODEL = "Amber 2 MQTT"
AMBER_FORECAST_DEVICE_ID = "amberforecast2mqtt"
AMBER_FORECAST_DEVICE_NAME = "Amber Forecast 2 MQTT"
AMBER_FORECAST_DEVICE_MODEL = "Amber Forecast 2 MQTT"
AEMO_DEVICE_ID = "aemo2mqtt"
AEMO_DEVICE_NAME = "AEMO 2 MQTT"
AEMO_DEVICE_MODEL = "AEMO NEM 2 MQTT"

DEVICE_MANUFACTURER = "Skynet"
DEVICE_SW_VERSION = "1.0"
AMBER_OBJECT_NAME = "Amber 5min Price Data"
AMBER_FORECAST_OBJECT_NAME = "Amber Forecast Price Data"
AMBER_OBJECT_VERSION = "1.0"
AEMO_OBJECT_NAME = "AEMO NEM 5min Price Data"
AEMO_OBJECT_VERSION = "1.0"

OBJECT_URL = "https://github.com/cabberley/amber2mqtt"

HOME_ASSISTANT_DISCOVERY_TOPIC = "homeassistant/device/"
AMBER_DISCOVERY_TOPIC = HOME_ASSISTANT_DISCOVERY_TOPIC + f"{AMBER_DEVICE_ID}/config"
AMBER_FORECAST_DISCOVERY_TOPIC = HOME_ASSISTANT_DISCOVERY_TOPIC + f"{AMBER_FORECAST_DEVICE_ID}/config"
AMBER_STATE_TOPIC_CURRENT = f"{AMBER_MQTT_PREFIX}/state"
AMBER_STATE_TOPIC_PERIODS = f"{AMBER_MQTT_PREFIX}/periods/state"
AMBER_STATE_TOPIC_5MIN_FORECASTS = f"{AMBER_MQTT_PREFIX}/forecasts5min/state"
AMBER_STATE_TOPIC_30MIN_FORECASTS = f"{AMBER_MQTT_PREFIX}/forecasts30min/state"
AMBER_STATE_TOPIC_USER_FORECASTS = f"{AMBER_MQTT_PREFIX}/forecastsuser/state"
AMBER_STATE_TOPIC_5MIN_EXTENDED_FORECASTS = f"{AMBER_MQTT_PREFIX}/forecasts5minExtended/state"

AEMO_DISCOVERY_TOPIC = HOME_ASSISTANT_DISCOVERY_TOPIC + f"{AEMO_DEVICE_ID}/config"
AEMO_STATE_TOPIC_CURRENT = f"{AMBER_MQTT_PREFIX}/aemo/state"
AEMO_STATE_TOPIC_PERIODS = f"{AMBER_MQTT_PREFIX}/aemo/periods/state"

AMBER_5MIN_CURRENT_GENERAL_ENTITY = "Amber 5min Current General Price"
AMBER_5MIN_CURRENT_FEED_IN_ENTITY = "Amber 5min Current Feed In Price"
AMBER_5MIN_CURRENT_AEMO_ENTITY = "Amber 5min Current AEMO Spot"
AMBER_5MIN_CURRENT_SPIKE_ENTITY = "Amber 5min Current Spike"
AMBER_5MIN_CURRENT_PERIOD_TIME_ENTITY = "Amber 5min Current Period Time"
AMBER_5MIN_LAST_UPDATE = "Amber 5min Current Last Updated"
AMBER_5MIN_CURRENT_GENERAL_DESCRIPTOR_ENTITY = "Amber 5min Current General Descriptor"
AMBER_5MIN_CURRENT_FEED_IN_DESCRIPTOR_ENTITY = "Amber 5min Current Feed In Descriptor"

AMBER_5MIN_FORECASTS_GENERAL_ENTITY = "Amber 5min Forecasts General Price"
AMBER_5MIN_FORECASTS_FEED_IN_ENTITY = "Amber 5min Forecasts Feed In Price"
AMBER_5MIN_FORECASTS_AEMO_ENTITY = "Amber 5min Forecasts AEMO Price"
AMBER_30MIN_FORECASTS_GENERAL_ENTITY = "Amber 30min Forecasts General Price"
AMBER_30MIN_FORECASTS_FEED_IN_ENTITY = "Amber 30min Forecasts Feed In Price"
AMBER_30MIN_FORECASTS_AEMO_ENTITY = "Amber 30min Forecasts AEMO Price"
AMBER_USER_FORECASTS_GENERAL_ENTITY = "Amber Billing Interval Forecasts General Price"
AMBER_USER_FORECASTS_FEED_IN_ENTITY = "Amber Billing Interval Forecasts Feed In Price"
AMBER_USER_FORECASTS_AEMO_ENTITY = "Amber Billing Interval Forecasts AEMO Price"
AMBER_5MIN_FORECASTS_EXTENDED_GENERAL_ENTITY = "Amber 5min Forecasts Extended General Price"
AMBER_5MIN_FORECASTS_EXTENDED_FEED_IN_ENTITY = "Amber 5min Forecasts Extended Feed In Price"

AEMO_NEM_SUMMARY_URI = "https://visualisations.aemo.com.au/aemo/apps/api/report/ELEC_NEM_SUMMARY"


AEMO_5MIN_CURRENT_PRICE_NSW = "AEMO 5min Current Price NSW"
AEMO_5MIN_CURRENT_PRICE_QLD = "AEMO 5min Current Price QLD"
AEMO_5MIN_CURRENT_PRICE_SA = "AEMO 5min Current Price SA"
AEMO_5MIN_CURRENT_PRICE_TAS = "AEMO 5min Current Price TAS"
AEMO_5MIN_CURRENT_PRICE_VIC = "AEMO 5min Current Price VIC"
AEMO_5MIN_LAST_UPDATE = "AEMO 5min Last Updated"

SENSOR_LIST_AEMO_CURRENT = [
    AEMO_5MIN_CURRENT_PRICE_NSW,
    AEMO_5MIN_CURRENT_PRICE_QLD,
    AEMO_5MIN_CURRENT_PRICE_SA,
    AEMO_5MIN_CURRENT_PRICE_TAS,
    AEMO_5MIN_CURRENT_PRICE_VIC,
]


SENSOR_LIST2 = []

SENSOR_LIST_CURRENT = [
    AMBER_5MIN_CURRENT_GENERAL_ENTITY,
    AMBER_5MIN_CURRENT_FEED_IN_ENTITY,
    AMBER_5MIN_CURRENT_AEMO_ENTITY,
    AMBER_5MIN_LAST_UPDATE,
    
]

SENSOR_LIST = [
    AMBER_5MIN_CURRENT_GENERAL_ENTITY,
    AMBER_5MIN_CURRENT_FEED_IN_ENTITY,
    AMBER_5MIN_CURRENT_AEMO_ENTITY,
]

SENSOR_FORECAST_5MIN_LIST = [
    AMBER_5MIN_FORECASTS_GENERAL_ENTITY,
    AMBER_5MIN_FORECASTS_FEED_IN_ENTITY,
    AMBER_5MIN_FORECASTS_AEMO_ENTITY,
]
SENSOR_FORECAST_30MIN_LIST = [
    AMBER_30MIN_FORECASTS_GENERAL_ENTITY,
    AMBER_30MIN_FORECASTS_FEED_IN_ENTITY,
    AMBER_30MIN_FORECASTS_AEMO_ENTITY,
]
SENSOR_FORECAST_USER_LIST = [
    AMBER_USER_FORECASTS_GENERAL_ENTITY,
    AMBER_USER_FORECASTS_FEED_IN_ENTITY,
    AMBER_USER_FORECASTS_AEMO_ENTITY,
]
SENSOR_FORECAST_5MIN_EXTENDED_LIST = [
    AMBER_5MIN_FORECASTS_EXTENDED_GENERAL_ENTITY,
    AMBER_5MIN_FORECASTS_EXTENDED_FEED_IN_ENTITY,
]




x=1
while x <= 12:
    SENSOR_LIST.append(f"Amber 5min Period {x} General Price")
    SENSOR_LIST.append(f"Amber 5min Period {x} Feed In Price")
    SENSOR_LIST.append(f"Amber 5min Period {x} AEMO Spot Price")
    x+=1

AMBER_DEVICE = {
        "identifiers": AMBER_DEVICE_ID,
        "name": AMBER_DEVICE_NAME,
        "model": AMBER_DEVICE_MODEL,
        "manufacturer": DEVICE_MANUFACTURER,
        "sw_version": DEVICE_SW_VERSION,
    }

AMBER_OBJECT = {
    "name":AMBER_OBJECT_NAME,
    "sw": AMBER_OBJECT_VERSION,
    "url": OBJECT_URL,
  }

AMBER_FORECAST_DEVICE = {
        "identifiers": AMBER_FORECAST_DEVICE_ID,
        "name": AMBER_FORECAST_DEVICE_NAME,
        "model": AMBER_FORECAST_DEVICE_MODEL,
        "manufacturer": DEVICE_MANUFACTURER,
        "sw_version": DEVICE_SW_VERSION,
    }

AMBER_FORECAST_OBJECT = {
    "name":AMBER_FORECAST_OBJECT_NAME, 
    "sw": AMBER_OBJECT_VERSION,
    "url": OBJECT_URL,
  }

AEMO_DEVICE = {
        "identifiers": AEMO_DEVICE_ID,
        "name": AEMO_DEVICE_NAME,
        "model": AEMO_DEVICE_MODEL,
        "manufacturer": DEVICE_MANUFACTURER,
        "sw_version": DEVICE_SW_VERSION,
    }

AEMO_OBJECT = {
    "name":AEMO_OBJECT_NAME,
    "sw": AEMO_OBJECT_VERSION,
    "url": OBJECT_URL,
  }
